### ISSUE TITLE
Why Generation and  Keyset?

### ISSUE THREAD

**Issue by jiangshilin** [TheCloudlessSky/NHibernate.Caches.Redis#14]
I have read the source, and I'm confused that why to store Generation and  Keyset?
1.Is there any condition to make serverGeneration and CacheNamespace.GetGeneration inconsistent?
2.When put a NH entity to redis, the put method also put it's cacheKey to a redis set, but it is never using again. Why?

**Comment by TheCloudlessSky** [comment]
1. Yes, the generation can be increased when [`Clear()` is called](https://github.com/TheCloudlessSky/NHibernate.Caches.Redis/blob/master/src/NHibernate.Caches.Redis/RedisCache.cs#L227) or if someone poked around Redis and deleted the cache keys (including the generation key). This means that an O(1) operation to clear the cache can be achieved by clearing the generation and having the next requests to the cache see that the generation is out of date.
2. The key it is put into a set so that they can be enumerated upon (for example by another tool). Otherwise, you'd have to use a `KEYS` command on your whole database in Redis just to find the matching NHibernate keys (really bad performance). For some of my applications, we expose the set in a UI so that we know what items are cached for the current generation.

**Comment by jiangshilin** [comment]
The keyset will occupy many redis's memory, and the memory is precious especially in production environment. So there should be a switch to close that feature.

**Comment by TheCloudlessSky** [comment]
The set only stores the key name (and it's serialized/compressed internally by Redis). I have several production instances where the *large* (> 100) cache key sets take up about 10KB of total memory. That shouldn't be much of a concern if you're worried about memory since your using this cache. If anything, you should be concerned about the cached values and how they're serialized to optimize for space.
