### ISSUE TITLE
Timeout performing SET

### ISSUE THREAD

**Issue by drake69** [TheCloudlessSky/NHibernate.Caches.Redis#24]
Hi,
without a defined pattern my code catch this error:

Timeout performing SET NHibernate-Cache:Medium:ACompany.FMS.Data.Objects.OperationStock.OilStockOperationBalance#77110:lock, inst: 0, mgr: ProcessReadQueue, err: never, queue: 0, qu: 0, qs: 0, qc: 0, wr: 0, wq: 0, in: 0, ar: 1, clientName: MIL-S-613, IOCP: (Busy=0,Free=1000,Min=24,Max=1000), WORKER: (Busy=0,Free=32767,Min=24,Max=32767), Local-CPU: 0% (Please take a look at this article for some common client-side issues that can cause timeouts: https://github.com/StackExchange/StackExchange.Redis/tree/master/Docs/Timeouts.md)

I've read the suggested page but I didn't fond anything that helps. Can you point me in the right way or help to solve, many thanks

**Comment by TheCloudlessSky** [comment]
Hey @drake69,

Timeouts are quite a complicated topic with respect to StackExchange.Redis (and Redis in general). In fact, I still [experience timeouts with StackExchange.Redis on Amazon ElastiCache](https://github.com/StackExchange/StackExchange.Redis/issues/351). Timeout exceptions is not something I can help with since it doesn't have anything to do with this project. You should log an issue with the StackExchange.Redis team (or search for existing timeout issues) and get more insight into your problem.

If you find that this issue _is_ related to this library, please let me know so I can re-open it.
