### ISSUE TITLE
NHibernate.Caches.Redis.2.0.0 dependency on nhibernate 3.3.1.4000

### ISSUE THREAD

**Issue by joesun99** [TheCloudlessSky/NHibernate.Caches.Redis#26]
Hi

Is there plan to build NHibernate.Caches.Redis.2.0.0 with new nhibernate 4.

Thx

Regards

**Comment by TheCloudlessSky** [comment]
Hey @joesun99,

A new build isn't required because the interfaces are backwards compatible. Follow these steps
1. Update to NHibernate 4.
2. Make sure you have a binding redirect in place in your `app/web.config` (e.g. I have `4.0.0.4000` installed):
   
   ``` xml
   <runtime>
       <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
           <dependentAssembly>
             <assemblyIdentity name="NHibernate" publicKeyToken="aa95f207798dfdb4" culture="neutral" />
             <bindingRedirect oldVersion="0.0.0.0-4.0.0.4000" newVersion="4.0.0.4000" />
           </dependentAssembly>
       </assemblyBinding>
   </runtime>
   ```
3. Run your application.

Please let me know if you have any issues with getting this set up.
