### ISSUE TITLE
Multiple session factories with different options

### ISSUE THREAD

**Issue by paulduran** [TheCloudlessSky/NHibernate.Caches.Redis#28]
Hi,

We are currently working on splitting our database into multiple 'shards'. Each shard will have it's own database connection/session factory and the next step is to configure each shard to have a separate redis store.

What I'd actually like to do is to to just use the **region name** to isolate the caches for each session factory.

Would it be possible to use the NHibernate redis cache in this way? To initialise the cache with different options for each session factory? The fact that `RedisCacheProvider.SetOptions` is static is giving me some doubts on whether this is achievable.

**Comment by TheCloudlessSky** [comment]
Hi @paulduran, thanks for your interest in the project!

Can you confirm for me how you'd like to separate each cache? Is the plan still to have a single Redis instance and the only thing separating the session factories is the region name prefix of all of the cache regions?

If the goal is to still use a single Redis instance (no sharding) and you're sharing the `ConnectionMultiplexer` for Redis, I believe you should still be able to use the static `RedisCacheProviderOptions` and then set the `RedisCacheConfiguration` for each model's specific region. For example if you have two model types for both session factory, you can just add both cache configurations for each.

If each session factory shares the same `RedisCacheProviderOptions` (cache configurations etc) and the only thing you want to change is the key prefix per-session factory, you should only need to configure the session factory to have a different cache region prefix (it should just work). See the [`cache.region_prefix` property for configuring NHibernate](http://nhibernate.info/doc/nhibernate-reference/session-configuration.html#configuration-optional-properties).

PS - The only reason (originally) that the `RedisCacheProviderOptions` is static is because NHibernate creates the `RedisCacheProvider`... we can't inject anything into. However, I've had a fix in mind for a while that could remove the need for the `RedisCacheProviderOptions` to be static. But, I'd like to see if we can solve your problem with what's there today. :smile:

**Comment by paulduran** [comment]
Hey @TheCloudlessSky ,

Thanks heaps for that suggestion! I don't know how I missed it.. But yep, that's all that was needed - to set the cache prefix when configuring the session factory.

I'm using FluentNHibernate so I just updated the setup code to be something like:

```
            .Cache(cache => cache.ProviderClass<RequestRecoveryRedisCacheProvider>()
                    .UseSecondLevelCache()
                    .RegionPrefix("CommonDb")
                    .UseQueryCache()
                )
```

thanks for your help!

**Comment by TheCloudlessSky** [comment]
Great! :smile:
