### ISSUE TITLE
Caching time 

### ISSUE THREAD

**Issue by anantupadhyay5786** [TheCloudlessSky/NHibernate.Caches.Redis#37]
Dear Cloudless Sky,

I am trying to use NHibernate.Caches.Redis in my project. Time taken to retrieve data from cache is more than normal DB call.
Our scenario is as : Suppose we have 200 entries in DB. We triggered select query. NHibernate.Caches.Redis loads each record into its cache. When the same select query is fired again then NHibernate.Caches.Redis loads the record from cache . But since serialization/deserialization of NHibernate.Caches.Redis is taking almost ~1ms for each and every record. Therefore the time taken in second select query from cache is almost 180 ms which is more than direct DB fetch because direct DB fetch is taking only 15 ms.
Please suggest a workaround for this problem.

**Comment by TheCloudlessSky** [comment]
Hey @anantupadhyay5786!

It sounds like your cache setup isn't aligned with your goals. Here's a few tips:

- Prefer caching the whole query rather than executing a SELECT and then loading each item from cache. It sounds like your executing an N+1 query. Try fixing this first.
- As a general rule, serialization/deserialization should be very fast. The built-in serializer should be pretty fast unless your object size is really big. Try reducing the size of the objects you're trying to cache, or swap out the `ICacheSerializer` for something faster like JSON or protobuf.
- Use caching at a higher layer. I'm not sure about your setup, but lets assume you're rendering HTML. Use another caching technique/library to wrap the HTML + query using something like generational caching (aka Russian Doll caching).
- Sometimes it is better to just call the DB directly rather than worrying about the cache. The best approach for this is to measure in production and use that data to help you make decisions.

Hope this helps!
